### ISSUE TITLE
Error when attempting to aggregate TSSs

### ISSUE THREAD

**Issue by zentnerlab** [zentnerlab/TSRexploreR#21]
`> exp <- tss_aggregate(exp)'`
`Error in `[.data.table`(x, , .(score = .N), by = .(seqnames, start, end,  : 
  column or expression 1 of 'by' or 'keyby' is type closure. Do not quote column names. Usage: DT[,sum(colC),by=list(colA,month(colB))]`

**Comment by rpolicastro** [comment]
fixed with #23
