### ISSUE TITLE
TSR hashing

### ISSUE THREAD

**Issue by gzentner** [zentnerlab/TSRexploreR#83]
While `format_counts` does add the FHASH column to TSRs, `mark_dominant` and `tsr_metrics` ask for TSR_FHASH, which only appears to be added by `associate_with_tsr`. I assume this is just an issue of non-matching column names?

**Comment by rpolicastro** [comment]
`TSR_FHASH` is added after `associate_with_tsr` is run, and is used by the functions `mark_dominant` and `tsr_metrics` to group TSSs together from the same TSR.

Various related improvements and bug fixes to `mark_dominant` and `tsr_metrics` are in PR #88
